volumes:
    postgres-data:
        external: true
    pg-admin:
        external: true
services:
    fastapi:
        environment:
            CORS_HOST: http://localhost:5173
            DATABASE_URL: postgresql://admin:password@postgres/fitconnect
            WAIT_HOSTS: postgres:5432
            SIGNING_KEY: 3635dd10c86b1fb68880e227d2a849883b911e53c941e070c5d18f2ef638ac5c

        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        environment:
            VITE_API_HOST: http://localhost:8000
        ports:
            - "5173:5173"
    postgres:
        image: postgres:14.5-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: admin
            POSTGRES_DB: fitconnect
        ports:
            - 15432:5432
    pg-admin:
        image: dpage/pgadmin4
        volumes:
            - pg-admin:/var/lib/pgadmin
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: kevitruon@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_DEFAULT_POSTFIX: 1
